### ISSUE TITLE
Remove files which are redundant for the engine

### ISSUE THREAD

**Issue by irisfaraway** [DEFRA/waste-carriers-engine#217]
When we turned the app into an engine, some of the files became redundant. We've cleared some of these out but it's possible there are others (especially in the config folder).

This may be a useful reference: https://www.amberbit.com/blog/2015/10/15/rails-mountable-engines/

**Comment by Cruikshanks** [comment]
Could compare what gets generated when you call `rails plugin new foo_bar --mountable` with what we have to spot what is redundant.

**Comment by irisfaraway** [comment]
Resolved by https://github.com/DEFRA/waste-carriers-engine/pull/421
